In [63]:
# problem formulation

In [64]:
# one vector x we find unit vector u  x->(x1,y1) , u->(x2,y2)
# for X1 point -> [ U^(T) X1 ] -> (x1x2+y1y2)

In [65]:
# variance 
#1/n sigma (n=1 to n) (x(i) - x(bar) )^(2) 

In [66]:
# variance find
# sigma(i=1 to n ) (U^(T) X(i) - U^(T) X(bar) )^(2) / n   == variance  -> mathematical objective function 

In [67]:
#find unit vector who have maximaum variances 

In [68]:
# we need to maximize this"sigma(i=1 to n ) (U^(T) X(i) - U^(T) X(bar) )^(2) / n " -> optimize problem

In [69]:
# covariance , covarince matrix

In [70]:
# mean don't give info about spread of data solve this problem we use -> vaiance 
#variance happen in one axis solve this problem we use -> covariance


In [71]:
#covariance -2/3 and 2/3 differnce of two data -> x increase y decrease
# corr (-1 to 1) but covarince is go up
# covarince use for two axis change how give that info

In [72]:
#2d data covarince matrix 
# 2*2 matrix 

In [73]:
# cov(x1,x1) -> var(x1) , cov(a,b) = cov(b,a)
#in matrix -> square, symmetric matrix
# [ varx(X1) cov(x1,x2) ]
# [ cov(x2,x1) , var(x2) ]

In [74]:
# cov matrix give spread of data and orientation 

In [75]:
# 3d cov for x,y,z
# [ varx ,c(x,y) ,c(x,z)]
# [ c(y,x), vary ,c(y,z) ]
# [ c(z,x), c(z,y) ,varz]

In [76]:
# eigen decomposition of cov matrix

In [77]:
# eigen vectors and eigen values -> matrices LT

In [78]:
# what are eigen vector -> special vector in that apply LT  vector not chnage directions 

In [79]:
# what is eigen values -> in 2d there is two vector that not change direction -> eigen vector and the factor is eigen values

In [80]:
# A v(->) = lamda v(->) this is true for eigen vector -> just change scale

In [81]:
# LT we use covariance matrix 

In [82]:
#steps in PCA 1)mean centric 2) find cov matrix 3) find the eigen value and eigen vecotr for cov matrix 
# if 3d then we get 3 vector of eigen vector and values a1,a2,a3 -> pc1,pc2,pc3 -> 3d to 1d -> pc1

In [84]:
# transformation points :
# 3d to 1d

In [1]:
import numpy as np
import pandas as pd

np.random.seed(23)

# Generate class 1 samples
mu_vec1 = np.array([0, 0, 0])
cov_mat1 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)
df = pd.DataFrame(class1_sample, columns=['feature1', 'feature2', 'feature3'])
df['target'] = 1

# Generate class 2 samples
mu_vec2 = np.array([1, 1, 1])
cov_mat2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)
df1 = pd.DataFrame(class2_sample, columns=['feature1', 'feature2', 'feature3'])
df1['target'] = 0

# Combine the DataFrames and shuffle
df = pd.concat([df, df1], ignore_index=True)
df = df.sample(40)


In [2]:
df.head()


feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1

In [24]:
# run in colab for visualization 
# import plotly.express as px
# #y_train_trf = y_train.astype(str)
# fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
#               color=df['target'].astype('str'))
# fig.update_traces(marker=dict(size=12,
#                               line=dict(width=2,
#                                         color='DarkSlateGrey')),
#                   selector=dict(mode='markers'))

# fig.show()


In [5]:
# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [6]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [8]:
# Step 3 - Finding EV and EVs
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)


In [9]:
eigen_values


array([1.3536065 , 0.94557084, 0.77774573])

In [10]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [14]:

# import plotly.graph_objects as go

# fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
#               color=df['target'].astype('str'))
# fig.update_traces(marker=dict(size=12,
#                               line=dict(width=2,
#                                         color='DarkSlateGrey')),
#                   selector=dict(mode='markers'))

# # Add eigen vectors to the plot
# for i in range(3):
#   fig.add_trace(go.Scatter3d(
#       x=[0, eigen_vectors[0][i]],
#       y=[0, eigen_vectors[1][i]],
#       z=[0, eigen_vectors[2][i]],
#       mode='lines',
#       line=dict(color='red', width=3)
#   ))


# fig.show()


In [15]:
pc = eigen_vectors[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [16]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

PC1       PC2  target
0  0.599433  1.795862       1
1  1.056919 -0.212737       0
2 -0.271876  0.498222       1
3 -0.621586  0.023110       1
4  1.567286  1.730967       1

In [23]:
# import plotly.io as pio
# pio.renderers.default = 'notebook'  # For classic Jupyter Notebook

# new_df['target'] = new_df['target'].astype('str')
# fig = px.scatter(x=new_df['PC1'],
#                  y=new_df['PC2'],
#                  color=new_df['target'],
#                  color_discrete_sequence=px.colors.qualitative.G10
#                 )

# fig.update_traces(marker=dict(size=12,
#                               line=dict(width=2,
#                                         color='DarkSlateGrey')),
#                   selector=dict(mode='markers'))
# fig.show()
     