In [4]:
import numpy as np
from sklearn.datasets import load_diabetes

In [5]:
X,y = load_diabetes(return_X_y=True)


In [6]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [7]:
X.shape

(442, 10)

In [8]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
from sklearn.model_selection import train_test_split
X_train , X_test,y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [10]:
X_train.shape

(353, 10)

In [11]:
y_train.shape

(353,)

In [12]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
reg = LinearRegression()

In [15]:
reg.fit(X_train,y_train)

LinearRegression()

In [16]:
y_pred = reg.predict(X_test)

In [17]:
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [18]:
print("R2 score",r2_score(y_test,y_pred))
r2 = r2_score(y_test,y_pred)

R2 score 0.4399338661568968


In [19]:
# b1 to b10
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [20]:
reg.intercept_

151.88331005254167

In [21]:
X_test.shape

(89, 10)

# making my own class

In [43]:
class MeraReg:
    def __init__(self):
        self.coef_=None
        self.intercept_ =None
        

    def fit(self,X_train,y_train):
        # b = (X^(T)X )^(-1) (X^T) Y
        X = np.insert(X_train,0,1,axis=1)
        betas = np.linalg.inv(X.T @ X ) @ (X.T) @ (y_train)
        # X_T = X.T
        # matrix = X_T @ X
        # matrix1 = np.linalg.inv(matrix) 
        # matrix2 = matrix1 @ X_T
        # matrix3 = matrix2 @ y_train
        # self.coef_ = matrix3[1:]
        # self.intercept_ = matrix3[0]
        self.intercept_=betas[0]
        self.coef_ = betas[1:]
        print(self.coef_)
        print(self.intercept_)
        
        

    def predict(self,X_test):
        # X = np.insert(X_test,0,1,axis=1)
        # B = np.insert(self.coef_,0,self.intercept_,axis=0)
        # y_pred = X @ B
        y_pred = X_test @ self.coef_ + self.intercept_ 
        return y_pred
        

In [38]:
class MeraLR:
    
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        
    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)
        
        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
    
    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred
        

In [44]:
mlr = MeraReg()

In [28]:
mlr = MeraLR()

In [45]:
mlr.fit(X_train,y_train)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.8833100525417


In [46]:
mlr.predict(X_test)

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [47]:
print("R2 score",r2_score(y_test,y_pred))
r2 = r2_score(y_test,y_pred)

R2 score 0.4399338661568968


In [49]:
mlr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [50]:
mlr.intercept_

151.8833100525417

In [29]:
import numpy as np
a = np.arange(6).reshape(3, 2)


In [38]:
import numpy as np

# Create an initial array
numbers = np.array([[0, 1, 3, 4],[1,2,3,4]])

# Insert the value 4 at index 2
result = np.insert(numbers, 2, 4,axis=1)

print(result)  # Output: [0 1 4 3 4]

[[0 1 4 3 4]
 [1 2 4 3 4]]


In [36]:
numbers

array([0, 1, 3, 4])